apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-root
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: shirokuma
spec:
  project: default
  source:
    repoURL: {{ required "repository.url is required" .Values.repository.url | quote }}
    targetRevision: {{ required "repository.revision is required" .Values.repository.revision | quote }}
    path: {{ required "repository.path is required" .Values.repository.path | quote }}
  destination:
    server: {{ required "destination.server is required" .Values.destination.server | quote }}
    namespace: {{ required "destination.namespace is required" .Values.destination.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
