apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/fluxcd/source-controller@sha256:4e9f7d179652cada516492ca341759fc07b5b7e58f7b57a5a9bfb631257c6d47
    target:
      kind: Deployment
      name: source-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/fluxcd/kustomize-controller@sha256:f5bc799e338bf779c55948adaee4c3eca83a833b98384c5fdef1674c1d658839
    target:
      kind: Deployment
      name: kustomize-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/fluxcd/helm-controller@sha256:6c8e17a0b9554bd6f9848595e832f6499a728d07db477b31cc53ce632d2ee6cc
    target:
      kind: Deployment
      name: helm-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/fluxcd/notification-controller@sha256:4fad21931eacf007a770b23fa5495201e4141ee5040218bac14ea90bee0ec996
    target:
      kind: Deployment
      name: notification-controller
